alpha: 0.9
batch_size: 8
debug: true
device: cuda:2
disable_lr_scheduler: false
iterations: 32768
loss_weights.coeff: 1.0
loss_weights.dm: 1.0
loss_weights.dx: null
lr_scheduler: step_lr
lr_scheduler_params.gamma: 0.5
lr_scheduler_params.step_size: 50
model: nn1_0
num_input_reduced_basis: 16
num_output_reduced_basis: 64
num_train_functions: 16
num_valid_functions: 256
optimizer: adamw
optimizer_params.lr: 0.005
optimizer_params.weight_decay: 1.0e-12
update_frequency: 100
verbose: false
