alpha: 0.9
batch_size.branch: 8
batch_size.trunk: all
debug: true
device: cuda:0
disable_lr_scheduler: true
iterations: 32768
loss_weights.dm: 1.0
loss_weights.dx: null
loss_weights.eval: 1.0
lr_scheduler: step_lr
lr_scheduler_params.gamma: 0.99
lr_scheduler_params.step_size: 50
model: nn1_0
num_reduced_basis: 16
num_train_functions: 16
optimizer: adamw
optimizer_params.lr: 0.001
optimizer_params.weight_decay: 1.0e-11
sampling_fraction: 0.1
update_frequency: 100
verbose: false
