batch_size.branch: 8
batch_size.trunk: all
debug: true
device: cuda:0
disable_lr_scheduler: false
iterations: 32768
loss_weights.dm: null
loss_weights.dx: null
loss_weights.eval: 1.0
lr_scheduler: step_lr
lr_scheduler_params.gamma: 0.6
lr_scheduler_params.step_size: 10
model: nn1_0
num_train_functions: 16
optimizer: adamw
optimizer_params.lr: 0.001
optimizer_params.weight_decay: 1.0e-06
sampling_fraction: 1.0
verbose: false
