alpha: 0.9
batch_size: 8
debug: true
device: cuda:0
dm_directions_name: Random
iterations: 32768
loss_weights.dm: 1.0
loss_weights.eval: 1.0
lr_scheduler: step_lr
lr_scheduler_params.gamma: 0.9
lr_scheduler_params.step_size: 50
model: nn1_3
num_dm_directions: 16
num_train_functions: 16
optimizer: adamw
optimizer_params.lr: 0.005
optimizer_params.weight_decay: 0.0001
update_frequency: 100
verbose: false
