num_test_functions: 500
num_reduced_basis: 16
num_test_dm_directions: 128
batch_size.branch: 8
batch_size.trunk: all
loss_weights.dm: 1.0
loss_weights.dx: null
loss_weights.eval: 1.0
test_milestones:
- 128
- 512
- 2048
- 8192
- 32768